### ISSUE TITLE
id=undefined

### ISSUE THREAD

**Issue by annevanderaar** [Oetzie/Internationalization#1]
I installed it as extra but the id=undefined on your page. See screeenshots. I use MODX Revolution 2.8.3-pl version
![Schermafbeelding 2021-11-03 om 10 57 20](https://user-images.githubusercontent.com/74538510/140044022-376919c3-a865-4fbe-b0f1-4b356abaea16.png)
![Schermafbeelding 2021-11-03 om 10 58 40](https://user-images.githubusercontent.com/74538510/140044028-db9dd65e-a75e-4dc9-b43e-533ab67ba686.png)
.

**Comment by Oetzie** [comment]
Fixed and released
