### ISSUE TITLE
Import translations topic field is not a selectbox

### ISSUE THREAD

**Issue by sdrenth** [Oetzie/Internationalization#2]
Import translations topic field is not a selectbox.

I expect this to be a selectbox just like it is in the export window where I can select a topic based on the selected namespace.
![Screenshot 2021-12-23 at 15 36 41](https://user-images.githubusercontent.com/7802465/147255039-07d0e53b-4369-40cc-bfaa-7f5a34fba2a3.png)

**Comment by Oetzie** [comment]
Fixed and released
